package com.sunzehai.mywebsite.constant;

public enum SqlFileCons {
	
	CATEGORY_SEL_001,
	CATEGORY_SEL_002,
	CATEGORY_SEL_003,
	ARTICLE_SEL_001,
	ARTICLE_SEL_002,
	ARTICLE_SEL_003,
	VIEW_CATEGORY_ARTICLE_COUNTS_SEL
	
}
